# Generated by Django 4.1 on 2022-08-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_user_doctor_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='users',
        ),
        migrations.AddField(
            model_name='doctor',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
