# Generated by Django 4.1 on 2022-08-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_rename_users_doctor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id', 'name']},
        ),
    ]
